# Generated by Django 3.2.19 on 2024-03-19 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=100, verbose_name=' Название проекта')),
                ('project_descriptions', models.CharField(max_length=255, verbose_name=' Описание')),
                ('project_date_start', models.DateField(verbose_name=' Дата создание')),
                ('project_date_end', models.DateField(verbose_name=' Дата окончания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('task_descriptions', models.CharField(max_length=255, verbose_name=' Описание задачи')),
                ('task_date_start', models.DateTimeField(verbose_name=' Дата создания задачи')),
                ('task_date_end', models.DateTimeField(verbose_name=' Дата окончания задачи')),
                ('task_priority', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'normal'), (4, 'medium'), (5, 'High')], default=1)),
                ('task_complexity', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'normal'), (4, 'medium'), (5, 'High')], default=1)),
                ('task_status', models.IntegerField(choices=[(1, 'Активный '), (2, 'На доработке'), (3, 'на проверке '), (4, 'Прогарающие'), (5, 'Просроченные'), (6, 'выполненные')], default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
