# Generated by Django 3.2.19 on 2024-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_date_status',
            field=models.IntegerField(choices=[(1, 'Активный'), (2, 'Прогарающие'), (3, 'Просроченные')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(1, 'На разработке'), (2, 'На проверке'), (3, 'На доработке '), (4, 'У аналитика на проверке'), (5, 'Выполнено')], default=1),
        ),
    ]
