# Generated by Django 3.2.19 on 2024-04-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_task_date_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='users',
        ),
    ]
