# Generated by Django 3.2.19 on 2024-04-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_projectmembership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='user',
        ),
    ]
