# Generated by Django 3.2.19 on 2024-04-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_rename_users_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembership',
            name='role',
        ),
    ]
