# Generated by Django 3.2.19 on 2024-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_joined_to_work',
            field=models.DateField(default='2022.10.10'),
        ),
    ]
