# Generated by Django 3.2.19 on 2024-03-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_user_data_joined_to_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level_tester',
        ),
    ]
