# Generated by Django 3.2.19 on 2024-03-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_level_level_tester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Manager'), (2, 'Developer Junior'), (3, 'Developer Middle'), (4, 'Developer Senior'), (5, 'Developer Teamlead'), (6, 'Tester'), (7, 'Analyst'), (8, 'Main Analyst')], default=1),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
