# Generated by Django 3.2.19 on 2024-04-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20240401_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_joined_to_work',
            field=models.DateField(null=True),
        ),
    ]
