# Generated by Django 3.2.19 on 2024-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_user_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bin',
            field=models.CharField(max_length=12, verbose_name='БИН Компании'),
        ),
    ]
